# Generated by Django 5.1.4 on 2024-12-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('original_image', models.ImageField(upload_to='signatures/original/')),
                ('signature_image', models.ImageField(upload_to='signatures/verify/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
